image:
  file: ./.devcontainer/Dockerfile
tasks:
  - before: sudo usermod -a -G sdkman gitpod && sudo usermod -a -G nvm gitpod && sudo chown -R gitpod /usr/local/sdkman /usr/local/share/nvm
  - init: ./mvnw install
vscode:
  extensions: 
  - redhat.vscode-xml
  - redhat.java
  - vscjava.vscode-java-debug
  - vscjava.vscode-java-test
  - vscjava.vscode-maven
  - vscjava.vscode-gradle
  - vmware.vscode-boot-dev-pack
  - shengchen.vscode-checkstyle
  - Dagger.dagger